# Generated by Django 5.1 on 2025-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='financials',
            name='revenue',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='original_language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(),
        ),
    ]
